
foreground              #E0DEF4
background              #191724
selection_foreground     #E0DEF4
selection_background     #403D52
cursor                  #524F67
cursor_text_color       #E0DEF4
url_color               #C4A7E7
active_border_color     #31748F
inactive_border_color   #403D52
bell_border_color       #F6C177
active_tab_foreground   #191724
active_tab_background   #C4A7E7
inactive_tab_foreground #E0DEF4
inactive_tab_background #1F1D2E
tab_bar_background      #191724
color0  #26233A
color8  #6E6A86
color1  #EB6F92
color9  #EB6F92
color2  #31748F
color10 #31748F
color3  #F6C177
color11 #F6C177
color4  #9CCFD8
color12 #9CCFD8
color5  #C4A7E7
color13 #C4A7E7
color6  #EBBCBA
color14 #EBBCBA
color7  #E0DEF4
color15 #E0DEF4

