
foreground              #FFFFFF
background              #271F19
selection_foreground     #FFFFFF
selection_background     #253B76
cursor                  #FFFFFF
cursor_text_color       #BFBFBF
url_color               #324883
active_border_color     #324883
inactive_border_color   #4C4C4C
bell_border_color       #FBDE2D
active_tab_foreground   #271F19
active_tab_background   #FF0080
inactive_tab_foreground #FFFFFF
inactive_tab_background #312923
tab_bar_background      #221A14
color0   #000000
color1   #9A1A1A
color2   #61CE3C
color3   #FBDE2D
color4   #324883
color5   #FF0080
color6   #8DA6CE
color7   #F8F8F8
color8   #4C4C4C
color9   #9A1A1A
color10  #61CE3C
color11  #FBDE2D
color12  #324883
color13  #FF0080
color14  #8DA6CE
color15  #F8F8F8

