
foreground              #C9C7CD
background              #161617
selection_foreground     #C1C0D4
selection_background     #2A2A2D
cursor                  #CAC9DD
cursor_text_color       #161617
url_color               #ACA1CF
active_border_color     #B9AEDA
inactive_border_color   #424246
bell_border_color       #F0C5A9
active_tab_foreground   #161617
active_tab_background   #ECAAD6
inactive_tab_foreground #C9C7CD
inactive_tab_background #202021
tab_bar_background      #111112
color0   #27272A
color1   #F5A191
color2   #90B99F
color3   #E6B99D
color4   #ACA1CF
color5   #E29ECA
color6   #EA83A5
color7   #C1C0D4
color8   #424246
color9   #FFAE9F
color10  #9DC6AC
color11  #F0C5A9
color12  #B9AEDA
color13  #ECAAD6
color14  #F591B2
color15  #CAC9DD

