#!/usr/bin/env bash
set -euo pipefail

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
THEMES_DIR="$DOTFILES/themes"
CURRENT_FILE="$DOTFILES/themes/.current"

# Adjust a hex color by an offset (positive=lighter, negative=darker)
adjust_color() {
    python3 -c "
h='${1}'.lstrip('#'); a=${2}
r,g,b=[max(0,min(255,int(h[i:i+2],16)+a)) for i in(0,2,4)]
print('#%02X%02X%02X'%(r,g,b))
"
}

list_themes() {
    for f in "$THEMES_DIR"/*.sh; do
        basename "$f" .sh
    done
}

current_theme() {
    [ -f "$CURRENT_FILE" ] && cat "$CURRENT_FILE" || echo "(none)"
}

apply_theme() {
    local theme="$1"
    local theme_file="$THEMES_DIR/${theme}.sh"

    if [ ! -f "$theme_file" ]; then
        echo "Theme not found: $theme"
        echo "Available: $(list_themes | tr '\n' ' ')"
        return 1
    fi

    # shellcheck disable=SC1090
    source "$theme_file"

    echo "==> Applying theme: $THEME_NAME"

    # ── Kitty ───────────────────────────────────────────────────
    echo "$KITTY_THEME" > "$DOTFILES/kitty/current-theme.conf"
    # Live reload: use OSC escape sequences via tmux passthrough
    local bg fg
    bg=$(echo "$KITTY_THEME" | grep -m1 '^background' | awk '{print $2}')
    fg=$(echo "$KITTY_THEME" | grep -m1 '^foreground' | awk '{print $2}')
    local cursor
    cursor=$(echo "$KITTY_THEME" | grep -m1 '^cursor ' | awk '{print $2}')
    if [ -n "${TMUX:-}" ]; then
        # Write OSC sequences to each pane's tty directly
        for pane_tty in $(tmux list-panes -a -F '#{pane_tty}'); do
            printf '\e]10;%s\e\\' "$fg" > "$pane_tty" 2>/dev/null || true
            printf '\e]11;%s\e\\' "$bg" > "$pane_tty" 2>/dev/null || true
            printf '\e]12;%s\e\\' "${cursor:-$fg}" > "$pane_tty" 2>/dev/null || true
            local i=0
            while [ $i -le 15 ]; do
                local c
                c=$(echo "$KITTY_THEME" | grep -m1 "^color${i} " | awk '{print $2}')
                [ -n "$c" ] && printf '\e]4;%d;%s\e\\' "$i" "$c" > "$pane_tty" 2>/dev/null || true
                i=$((i + 1))
            done
        done
    else
        printf '\e]10;%s\e\\' "$fg" > /dev/tty
        printf '\e]11;%s\e\\' "$bg" > /dev/tty
    fi
    echo "    kitty ✓"

    # ── Tmux ────────────────────────────────────────────────────
    # Extract background from kitty theme to compute pane dimming
    local bg
    bg=$(echo "$KITTY_THEME" | grep -m1 '^background' | awk '{print $2}')
    local dim_bg active_border inactive_border
    if [ "$NVIM_BACKGROUND" = "light" ]; then
        dim_bg=$(adjust_color "$bg" -30)
        active_border=$(echo "$KITTY_THEME" | grep -m1 'active_border_color' | awk '{print $2}')
        inactive_border=$(adjust_color "$bg" -20)
    else
        dim_bg=$(adjust_color "$bg" 30)
        active_border=$(echo "$KITTY_THEME" | grep -m1 'active_border_color' | awk '{print $2}')
        inactive_border=$(adjust_color "$bg" 15)
    fi

    cat > "$DOTFILES/themes/.tmux-theme.conf" <<TMUX
${TMUX_THEME}
# Active window tab highlight (auto-generated)
set -g window-status-current-format ' #I:#W '
set -g window-status-format ' #I:#W '
set -g window-status-current-style 'bg=${active_border},fg=${bg},bold'
# Active/inactive pane distinction (auto-generated)
set -g window-style 'bg=${dim_bg}'
set -g window-active-style 'bg=${bg}'
set -g pane-active-border-style 'fg=${active_border}'
set -g pane-border-style 'fg=${inactive_border}'
set -g pane-border-lines heavy
set -g pane-border-indicators arrows
TMUX
    # Live reload if tmux is running
    if command -v tmux &>/dev/null && tmux list-sessions &>/dev/null; then
        tmux source-file "$DOTFILES/themes/.tmux-theme.conf" 2>/dev/null || true
    fi
    echo "    tmux ✓"

    # ── Neovim ──────────────────────────────────────────────────
    cat > "$DOTFILES/themes/.nvim-theme.lua" <<EOF
-- Auto-generated by set-theme.sh — do not edit
vim.o.background = "${NVIM_BACKGROUND}"
${NVIM_SETUP}
vim.cmd.colorscheme("${NVIM_COLORSCHEME}")

-- Transparent Normal bg so tmux inactive pane dimming shows through
vim.api.nvim_set_hl(0, "Normal", { bg = "NONE" })
vim.api.nvim_set_hl(0, "NormalNC", { bg = "NONE" })
EOF
    # Live reload running nvim instances
    local socks
    socks=$(find /tmp /var/folders "${XDG_RUNTIME_DIR:-/dev/null}" -name "nvim.*.0" -type s 2>/dev/null || true)
    for sock in $socks; do
        [ -S "$sock" ] 2>/dev/null && nvim --server "$sock" --remote-send \
            ":luafile $DOTFILES/themes/.nvim-theme.lua<CR>" 2>/dev/null || true
    done
    echo "    nvim ✓"

    # ── fzf ─────────────────────────────────────────────────────
    echo "export FZF_DEFAULT_OPTS=\"\$FZF_DEFAULT_OPTS --color=${FZF_COLORS}\"" \
        > "$DOTFILES/themes/.fzf-theme.sh"
    echo "    fzf ✓"

    # ── LS_COLORS ───────────────────────────────────────────────
    if command -v vivid &>/dev/null; then
        echo "export LS_COLORS=\"$(vivid generate "${VIVID_THEME}")\"" \
            > "$DOTFILES/themes/.ls-colors-theme.sh"
    else
        echo "# vivid not installed, LS_COLORS not set" \
            > "$DOTFILES/themes/.ls-colors-theme.sh"
    fi
    echo "    ls_colors ✓"

    # ── Kiro CLI ────────────────────────────────────────────────
    if command -v kiro-cli &>/dev/null && [ -n "${KIRO_THEME:-}" ]; then
        kiro-cli theme "$KIRO_THEME" 2>/dev/null || true
        echo "    kiro-cli ✓"
    fi

    # ── Hot-reload shell env via tmux ───────────────────────────
    if command -v tmux &>/dev/null && tmux list-sessions &>/dev/null; then
        # Reload env in all running shell panes
        local reload_cmd="source ~/dotfiles/themes/.fzf-theme.sh; source ~/dotfiles/themes/.ls-colors-theme.sh"
        for pane in $(tmux list-panes -a -F '#{pane_id}'); do
            local cmd
            cmd=$(tmux display-message -p -t "$pane" '#{pane_current_command}')
            case "$cmd" in
                bash|zsh|sh|fish)
                    tmux send-keys -t "$pane" " $reload_cmd" Enter
                    ;;
            esac
        done
    fi

    # ── Save current ────────────────────────────────────────────
    echo "$theme" > "$CURRENT_FILE"
    echo "==> Theme set to: $THEME_NAME"
}

pick_theme() {
    if ! command -v fzf &>/dev/null; then
        echo "fzf not found. Usage: set-theme.sh <theme-name>"
        echo "Available: $(list_themes | tr '\n' ' ')"
        return 1
    fi

    local current
    current="$(current_theme)"

    local choice
    choice=$(list_themes | fzf \
        --prompt="Theme (current: $current)> " \
        --preview="cat $THEMES_DIR/{}.sh | grep -E '^(THEME_NAME|NVIM_|KITTY_THEME|background)' | head -10" \
        --preview-window=right:40%)

    [ -n "$choice" ] && apply_theme "$choice"
}

# ── Main ────────────────────────────────────────────────────────────
case "${1:-}" in
    "")       pick_theme ;;
    --list)   list_themes ;;
    --current) current_theme ;;
    *)        apply_theme "$1" ;;
esac
