# .zshrc

export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Compilation flags
export ARCHFLAGS="-arch $(uname -m)"

export TERM_EDITOR=nvim
export EDITOR=nvim

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

#set color to 256
export TERM=xterm-256color

# PATH
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/usr/local/anaconda3/bin:$PATH"
export PATH="$HOME/Library/Android/sdk/build-tools/30.0.3:$PATH"
export PATH="$HOME/.gem/ruby/X.X.0/bin:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="$HOME/jdtls/bin:$PATH"
export PATH=$PATH:/Users/yikunliu/.toolbox/bin

# Java
export JAVA_HOME=$(/usr/libexec/java_home -v 1.17)
export JAVA_TOOLS_OPTIONS="-Dlog4j2.formatMsgNoLookups=true"

#fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS='--color=bg+:#302D41,bg:#1E1E2E,spinner:#F8BD96,hl:#F28FAD --color=fg:#D9E0EE,header:#F28FAD,info:#DDB6F2,pointer:#F8BD96 --color=marker:#F8BD96,fg+:#F2CDCD,prompt:#DDB6F2,hl+:#F28FAD'

fpath=($fpath "$HOME/.zfunctions")

source ~/dotfiles/zsh/myalias
source ~/amazon

export GOPROXY="direct"
export NOTES_DIR="~/OneDrive/sync/notes"
export XDG_DATA_DIRS="/opt/homebrew/share"
